### ISSUE TITLE
Adapt the persona bar extension to the same build processes as the other extensions

### ISSUE THREAD

**Issue by WillStrohl** [UpendoVentures/generator-upendodnn#13]
See title.

**Comment by hismightiness** [comment]
Instead of doing that...  It may be better to integrate the example from David Poindexter. 🤔

**Comment by WillStrohl** [comment]
Delaying this.  It appears to be too much work, as it's no longer matching current development standards.

**Comment by WillStrohl** [comment]
We've instead decided to replace the persona bar template entirely with a new one using VueJS.
