### ISSUE TITLE
Incorrect folders included in MVC solution

### ISSUE THREAD

**Issue by dschill** [UpendoVentures/generator-upendodnn#15]
## Describe the bug
  In the views folder, there is a reference to Edit/Index inside an “Items” folder but the correct folder is “Example”.  The correct folder is in place in the file system but the reference in Visual Studio points to the “Items” folder.  

## To Reproduce
1 Generate a new MVC project 
2 Open project using visual studio 2017
3 Navigate to the views folder and click on "Items" then click on either of the cshtml files in the folder

## Expected behavior
files in items folder should be accessible

## Errors
Paste the error(s) related to this issue.

**Comment by hismightiness** [comment]
FYI - This issue was resolved in a release pushed yesterday.  (Also, another release was just now published. 😄)
