### ISSUE TITLE
Receiving error message that MSBuild was not found

### ISSUE THREAD

**Issue by rickriggs** [UpendoVentures/generator-upendodnn#16]
## Describe the bug
After following steps in Readme, receiving message when generating module (MVC or WebForms) 'Yikes! A valid version of MSBuild was not Found!  This is a critical error.

Currently have Visual Studio Community 2017 v. 15.9.7 and VS Build Tools 2017, v. 15.9.7 installed running on Windows 10.  I did also try uninstalling MSBuildTools, cleaning up older versions of VisualStudio and then installing MSBuildTools from the link in the Readme.

The solution and module build correctly, but there are not build scripts to build the install and release modules.

## To Reproduce
Followed steps exactly as outlined in the readme.md

## Screenshots
![image](https://user-images.githubusercontent.com/29731204/53511081-bf383b80-3a7c-11e9-8c33-8a04ba20137f.png)

Thank you for your work on this and sharing with the community!

**Comment by rickriggs** [comment]
I am not certain what happened, but I believe this was something unique to my machine.  I had older versions of VS and MSBuild.  I did some additional clean up, reboot, and now everything works correctly per the Readme.  Closing.  Sorry to take up your time.

**Comment by hismightiness** [comment]
Thanks for the update, Rick! :)
