### ISSUE TITLE
VueJS Template's API calls are relative to page path

### ISSUE THREAD

**Issue by ryanjagdfeld** [UpendoVentures/generator-upendodnn#212]
## Describe the bug  
The API calls return error 404 when a module built from the VueJS SPA template is placed on a page more than one level deep.

## Software Versions  
- DNN:  09.12.00  
- Visual Studio:  2022/17.6.2

## To Reproduce  
1. Setup a new project scaffold and create a VueJS SPA module using the template.
2. Build and install the module on a fresh DNN instance.
3. Add a new page to the root, then add a child page under that one (i.e. www.mydomain.com/Inner-Page/Inner-Inner-Page)
4. Add the VueJS SPA module to the inner inner page.
5. See 404 error in console and under Quick Settings

## Expected behavior  
Working API calls

## Actual behavior  
404 error on API calls. 

## Additional context
A quick work around for my situation was to change the baseUrl setting in the ItemView.js and QuickSettings.js files.  Instead of: 
```
var svc = {
        moduleid: moduleid,
        baseUrl: "DesktopModules/MyVueModule/API/",
        framework: $.ServicesFramework(moduleid)
    };
```
I added a '/' to always be the root:
```
var svc = {
        moduleid: moduleid,
        baseUrl: "/DesktopModules/MyVueModule/API/",
        framework: $.ServicesFramework(moduleid)
    };
```

If this is the correct fix, please let me know, I can create a PR with the change to the template.

**Comment by VAlmea** [comment]
@ryanjagdfeld I tested the requested changes and it's a correct fix. Thanks for your comment
