### ISSUE TITLE
Vue 3 Project Not calling correct API URL when getting localized resources.

### ISSUE THREAD

**Issue by BillyShelton** [UpendoVentures/generator-upendodnn#294]
## Sponsorship  

If this request requires additional support (e.g., such as direct email/phone/meeting/development), I have the following interest in helping to [sponsor the effort via GitHub Sponsors](https://github.com/sponsors/UpendoVentures):    

- [ ] None, please continue to work for me for free :P  
- [ ] Absolutely, I get value out of this!  
- [ ] Maybe later  
- [x] I'm already a sponsor... Woot!  

## Describe the bug  
A module generated with the Vue 3 template does not work on a subpage. It works fine on a root level page. The localized resources are trying to call the wrong URL when the module is installed on a subpage.  For example, given `rootpage `and `subpage`, the call to get the `resx.Welcome` on the `HomeItem` template will be: `https://mydomain.com/subpage/API/<module>/Resx/GetResx?filename=View` when it should be `https://mydomain.com/API/<module>/Resx/GetResx?filename=View`.

Additionally, if you are using a portal that was set up with Site Type = Directory, the module localized resources will not work. 

## Software Versions  
- DNN:  09.13.01 (0)  
- Hotcakes:  N/A
- Visual Studio:  2022

## To Reproduce  
1. Use the generator to generate a solution
2. Use the generator to generate a new Vue 3 module
3. Install DNN 9.13.01 to the website folder in the solution
4. Build and install the module
5. Create a page on DNN then create a subpage. 
6. Add the new Vue 3 module to the subpage.

## Expected behavior  
The module should work on a subpage of the site.

## Actual behavior  
The module does not show content because the request for the localized resource is returning a 404.

**Comment by BillyShelton** [comment]
Additionally, if you are using a site with Site Type = Directory, the Items API call will not use the correct URL.

**Comment by WillStrohl** [comment]
Hello @BillyShelton ...  Thank you for reporting this issue and for being a sponsor.  We've documented this internally and will have a PR to fix it for you ASAP.  💪🏽
