### ISSUE TITLE
SI: Vue 3: The generated module can only be used by Super Users.

### ISSUE THREAD

**Issue by BillyShelton** [UpendoVentures/generator-upendodnn#303]
## Sponsorship

If this request requires additional support (e.g., such as direct email/phone/meeting/development), I have the following interest in helping to [sponsor the effort via GitHub Sponsors](https://github.com/sponsors/UpendoVentures):

- [ ] None, please continue to work for me for free :P
- [ ] Absolutely, I get value out of this!
- [ ] Maybe later
- [x] I'm already a sponsor... Woot!

## Describe the bug

The template as built will not allow a non-SuperUser to call either the `ItemController` or the `ResxController` even if the Authorization Attributes on the controllers are changed.

## Software Versions

- DNN: 09.13.01
- Visual Studio: 2022

## To Reproduce

1. User the generator to generate the default Vue 3 module.
2. Place the module on a page.
3. Add an Administrator user to the DNN instance.
4. View the page as the Administrator.

## Expected behavior

I expect an Administrator to be able to see and add/edit items.

## Actual behavior

No Items are shown and all API calls return 401 - unauthorized errors.

## Additional context

Changing the Authorization Attributes on the controllers does not resolve the issue.  For comparison, the React Template handles Authorization correctly on the API's.

**Comment by WillStrohl** [comment]
Thanks for reporting this, Billy, and for being a sponsor.  We'll get to this as soon as we can.

**Comment by alejoroman0605** [comment]
@BillyShelton you just have to change the access level in the controller from [Authorize] to [DnnAuthorize]. This is in case they authenticate with any user in any role.

![image](https://github.com/UpendoVentures/generator-upendodnn/assets/48692645/5f23aa91-9be4-447e-b8f4-1b161c2d3ec1)
![image](https://github.com/UpendoVentures/generator-upendodnn/assets/48692645/aa5c286d-74ad-48c2-a41b-f8f6478ad9e0)

![image](https://github.com/UpendoVentures/generator-upendodnn/assets/48692645/8daf8366-96fe-4eb2-89a3-7ea200505875)
![image](https://github.com/UpendoVentures/generator-upendodnn/assets/48692645/c5699315-29f2-48ca-9262-6e15a1df54b5)

In case the page does not require authentication, you can use [AllowAnonymous] or implement authorization by apiKey if you want to keep the API secure and this depends on what you want to achieve with the module.
Regards,

**Comment by BillyShelton** [comment]
@alejoroman0605 
In the React Module, if I want users with View permission on the module to be able to call the GetAll and GetById API's and only users with Edit permission to call the Create/Update/Delete API's, I would use:

```
  [SupportedModules("MyReactModule")]
  public class ItemController : ApiControllerBase
```

then add

`   [DnnModuleAuthorize(AccessLevel = SecurityAccessLevel.View)]`
on the GetAll & GetById actions and

`   [DnnModuleAuthorize(AccessLevel = SecurityAccessLevel.Edit)]`
on the Create/Update/Delete actions.  

How would I accomplish this with the Vue 3 template?

Additionally the other security related attributes do not seem to be functioning properly:

- `[ValidateAntiForgeryToken]`
- `[SupportedModules("MyVueModule")]`

Whenever I attempt to add these attributes I get a 401 unauthorized error for all calls to that controller/action.

**Comment by WillStrohl** [comment]
The 1.12.4 release should resolve this issue.
