### ISSUE TITLE
Error when using with VS 2017 community edition

### ISSUE THREAD

**Issue by pstudies** [UpendoVentures/generator-upendodnn#32]
## Describe the bug
When using the template to generate DNN modules with VS 2017 community edition the following error is reported:

"Yikes!! A valid version of MS build was not found. This is an critical error ..... :( "

## To Reproduce
1. Follow instructions of this [page](https://upendoventures.com/Blog/save-hundreds-of-hours-building-dnn-modules-and-other-types-of-extensions4)
2. Ensure you have VS 2017 community edition installed
3. Create a solution project
4. Now try to create a Web forms module project.

## Expected behavior
A new web forms module should get created

## Errors
"Yikes!! A valid version of MS build was not found. This is an critical error ..... :( "

## Additional context
The solution to this issue is to add the following line to DnnGeneratorBase.js 

if (fs.existsSync("C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Microsoft\\VisualStudio\\v15.0\\WebApplications\\Microsoft.WebApplication.targets")){
msBuildVersion = "15"; // VS 2017
}

Add the above code at line # 192

**Comment by hismightiness** [comment]
This is an expected error.  Please see the README in the root of this project.  :)
