### ISSUE TITLE
Implement case sensitivity for first letter of company/namespace and extension

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/generator-upendodnn#35]
## Describe the bug
Currently, the first letter of the company/namespace and extensions are capitalized by default.  This is not ideal.

## To Reproduce
1. Create any extension (e.g., skin object)
2. Enter company/namespace that starts with lower case first letter
3. Enter extension name that starts with lower case first letter
4. See that the above first letters are now uppercase in scaffolded project

## Expected behavior
Scaffolding should respect the case of first letters entered.

## Screenshots
n/a

## Errors
n/a

## Additional context
n/a

**Comment by hismightiness** [comment]
This is not due to the generator itself, but rather a third-party integrated tool that ensures camel-basing.  I think changing the behavior would require a workaround to compare the original and resulting values, then changing it to match after the fact.  

My only concern with implementing this workaround is that the implemented camel casing is considered to be best practice with standard naming conventions and it could incidentally encourage lazy/bad coding practices.  Thoughts?

**Comment by david-poindexter** [comment]
Okay, gotcha.  This would honestly probably keep us from using the tool due to our need for all specific casing.  Perhaps we could just maintain a fork for our use that does not leverage this third-party tool.  I am just not sure how involved it would be to remove/change.  Which package/tool is it?

**Comment by hismightiness** [comment]
Looking...

**Comment by hismightiness** [comment]
It's included here:

https://github.com/UpendoVentures/generator-upendodnn/blob/master/generators/lib/DnnGeneratorBase.js#L5

And implemented here:

https://github.com/UpendoVentures/generator-upendodnn/blob/master/generators/skinobject/index.js#L76-L77

**Comment by hismightiness** [comment]
Lower-case company names is probably the 20 of the 80/20 product management guideline that we often try to follow.  :) 

I know it's one extra step for you, but would it be possible just to do a find and replace after adding, or would a code-based workaround be better?  I just want to have the tool automate best practices as much as possible.

**Comment by hismightiness** [comment]
Another possibility is to somehow add a configuration override file to allow for edge cases like this.  🤔

**Comment by david-poindexter** [comment]
Thanks @hismightiness.  The number of manual steps to change based on the current tooling is not quick and easy (modifications to *.sln file, *.csproj file, all namespaces, manifest, MSBUILD, etc.).  It is not for the novice for sure.  I do like the idea of an override configuration or special command line parameter (with warnings about _best practices_ if necessary).

**Comment by hismightiness** [comment]
Find and replace has always worked for me.  🤔 

In the next release, you can add `-f` to the end of the name to override the casing functionality.  For example...

`nvisionative -F`

Will end up naming the solution/project/namespace as `nvisionative`.

Whereas, just entering `nvisionative` by itself will end up being `Nvisionative` in the solution/project/namespace.
