### ISSUE TITLE
Fix import statements in MSBuild files for skin object project type

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/generator-upendodnn#36]
## Describe the bug
Newly generated skin object projects cannot be opened due to ../../Build not existing.

## To Reproduce
1. Generate new skin object project
2. Try to open the VS solution file
3. See errors

## Expected behavior
Solution/project should open with no issues.  I am not sure why it is referencing things that do not exist.

## Screenshots
n/a

## Errors
Something like...
`The imported project [files] do not exist.`

## Additional context
n/a

**Comment by hismightiness** [comment]
Did you first run the solution scaffold in the same folder?

**Comment by david-poindexter** [comment]
Not sure what you mean.  What is the `Solution` scaffold?  Sorry if I missed this in the documentation somewhere.

**Comment by hismightiness** [comment]
For now, until Issue #2 is implemented, all of the projects are fully dependent on the `Solution` scaffold being run in the folder first.  Then, you add as many of the other scaffolds in the same folder, ideally adding them to the primary solution you initially created.  This isn't formally "written" anywhere here yet, but it is in the video on the [README](https://github.com/UpendoVentures/generator-upendodnn#generator-upendodnn---).  :)

**Comment by hismightiness** [comment]
I only asked that because I didn't get the same result as you, but I first added the `Solution` scaffold, which I assume is the difference since I don't see that in the bug report above.  :)

**Comment by hismightiness** [comment]
Added steps for first-timers.  :)  

https://github.com/UpendoVentures/generator-upendodnn/blob/master/README.md#first-timers-how-to-use

**Comment by david-poindexter** [comment]
Thanks @hismightiness.  That now makes sense.  I'll have to make sure this matches our use case because it seems like considerable overhead for stand-alone solutions (like a simple skin object), but I certainly see the value in this architecture for multi-project solutions.  Thanks again for this great open-source initiative!

I'll circle back to this issue as soon as I've had time to test.  I'll close it out if all is well.
