### ISSUE TITLE
Cannot create a SPA project

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/generator-upendodnn#37]
## Describe the bug
When creating a SPA project an error is thrown.

## To Reproduce
1. Use `yo upendodnn` to create a `Solution`
2. Use `yo upendodnn` to create a SPA project
3. See error

## Expected behavior
No errors.

## Screenshots
![ScreenCapture_ 2019-10-08 05 01 PM _2514](https://user-images.githubusercontent.com/4568451/66437673-63f9fe80-e9f8-11e9-80a9-fe23efa82f9b.jpg)

## Errors
See screenshot.

## Additional context
n/a

**Comment by WillStrohl** [comment]
This has since been replaced with newer SPA templates to resolve many of the previous issues.
