### ISSUE TITLE
Wonky References in MVC Project

### ISSUE THREAD

**Issue by dowdian** [UpendoVentures/generator-upendodnn#38]
## Describe the bug
After creating a new MVC project using the generator, several of the using statements in the Views throw errors saying things like "The type or namespace name 'DotNetNuke' could not be found (are you missing a using directive or an assembly reference?)". This prevents any Intellisence in the document from working.

The funny thing is, this issue does not exist in the Models or Controllers and it does not impact my ability to successfully compile or run the application. That works as expected.

## To Reproduce
I'm using the following versions:

1. DNN_Platform_9.4.1_Install
2. generator-upendodnn 01.02.02

1. Use yo upendodnn to create a Solution
2. Use yo upendodnn to create a MVC project
3. Open the solution in Visual Studio and open the Index.cshtml file.
4. Note the red squigglies.

## Expected behavior
I should be expected to make my own red squigglies and Intellisence should work like it does elsewhere in the project.

## Screenshots
![image](https://user-images.githubusercontent.com/13598731/66893878-bc805b80-eff7-11e9-817d-0e0cbac3aaf3.png)

## Errors
Error	CS0234	The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0234	The type or namespace name 'Helpers' does not exist in the namespace 'System.Web' (are you missing an assembly reference?)	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0234	The type or namespace name 'WebPages' does not exist in the namespace 'System.Web' (are you missing an assembly reference?)	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0234	The type or namespace name 'WebPages' does not exist in the namespace 'System.Web' (are you missing an assembly reference?)	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0246	The type or namespace name 'DotNetNuke' could not be found (are you missing a using directive or an assembly reference?)	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0115	'_Page_Views_CaseList_Index_cshtml.Execute()': no suitable method found to override	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0103	The name 'Context' does not exist in the current context	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	1		Active
Error	CS0103	The name 'Dnn' does not exist in the current context	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	9		Active
Error	CS0103	The name 'Model' does not exist in the current context	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	10		Active
Error	CS0103	The name 'Url' does not exist in the current context	12_Views_CaseList_Index.cshtml	C:\Dev\DowdianDNN\Modules\CentPro\Views\CaseList\Index.cshtml	25		Active

Some of the messages above are repeated multiple times in the VS Error List.

## Additional context
In addition to being a very lazy developer, I'm also getting pretty old. I really need my Intellisence because typing is hard. Just writing this submission has exhausted me. I going to go take a nap.

Thank you so much for any help you can offer.

**Comment by dowdian** [comment]
I'm getting desperate for any help. Has anyone else experienced this issue?

**Comment by dowdian** [comment]
This issue has been resolved.

**Comment by dowdian** [comment]
This issue has been resolved.

**Comment by AliAminiP** [comment]
> This issue has been resolved.

hey @dowdian 
I'm so glad to you've handled the issue
can you explain how?
Best regards

**Comment by dowdian** [comment]
To be honest, that was a "rage quit" because I wasn't getting any response and I needed to press on. The issue was not resolved at that point, nor for many months to come.

I have since found a resolution to this issue by updating to a more recent version of Upendo. There were several during 2020, and I'm afraid I don't remember which one.

**Comment by AliAminiP** [comment]
> To be honest, that was a "rage quit" because I wasn't getting any response and I needed to press on. The issue was not resolved at that point, nor for many months to come.
> 
> I have since found a resolution to this issue by updating to a more recent version of Upendo. There were several during 2020, and I'm afraid I don't remember which one.

Tnx for reply
by the way, I solved it
it's because of assembly reference error in one of my shared project
and for resolving intellisense error (intellisense does not work in views) add bin folder to each project and reference assemblies from there 

best regards
