### ISSUE TITLE
Namespace for your solution

### ISSUE THREAD

**Issue by AndreasDecke** [UpendoVentures/generator-upendodnn#49]
## Describe the bug
Create a Library, give the name CebiCon.MyPackage.Modules
the generator make CebiConMyPackageModules.Libraries.MvcData.csproj Projectfile and the
Namespace is:

```
namespace CebiConMyPackageModules.Libraries.MvcData
{
	/// <summary>
    /// ExampleClass - DB Access for all MVC Modules
    /// </summary>
	public static class ExampleClass
	{
		public const string DEFAULT = "Yay! I exist!";
	}
}
```

correct would be "namespace CebiCon.MyPackage.Modules.Libraries.MvcData"
the points are missing

**Comment by hismightiness** [comment]
This is actually the intended result.  The value you entered is supposed to help generate the namespace, not be the namespace.  Sorry for the confusion.  :)
